export const GET_NOTES_LIST = "GET_NOTES_LIST";
export const CREATE_NEW_NOTE = "CREATE_NEW_NOTE";
export const DELETE_SINGLE_NOTE = "DELETE_SINGLE_NOTE";
export const CLEAR_NOTES_DATA = "CLEAR_NOTES_DATA";
